### PR TITLE
adds ‘configuration’ parameter to encode/decode functions

### PR DESCRIPTION
**Pull request by daSkier**
adds a ‘delimiter’ parameter to decoding functions to support other delimiters like “\t”. Where these delimiter parameters have been added a default has been set to “,” to maintain the current functionality.

Adding similar functionality to the encode functions should probably be considered if this approach is considered as a long term solution.

### CODE REVIEW

**Comment by proggeramlug** [comment]
At first glance, it looks great to me. @calebkleveter as the maintainer of this package will have the final say for approval.

**Comment by daSkier** [comment]
I agree. I think a configuration struct is a better long-term approach. I alluded to this in the issue I opened on the subject. 

Do you have a list of the potential options you'd like to include? 

If you have a list of your preferred options for the configurations I can look into trying to pull together an implementation. I'll caution that it might take me a bit since it's now the work week (I'm a mechanical engineer and software is a side project).

**Comment by proggeramlug** [comment]
@daSkier Time is not of the essence here, we operate more like Apple: Do it right instead of quick. ;)

**Comment by calebkleveter** [comment]
We might want to allow configuring for what row delimiters are used and if the cells are surrounded by quotes or not. By doing that we should be able to make parsing faster because we don't need to check for edge cases.

I totally understand not being able to work on this very much. I've got my own side projects that get very little work because of that 😄.

**Comment by daSkier** [comment]
@calebkleveter @proggeramlug I've created a `Config` struct to be passed into both the Serializer and Parser. I've added a `configuration: Config = Config()` parameter to all of the functions that seemed pertinent and allow existing code to work. 

```Swift
public struct Config {
    public let delimiter: Character
    public let inQuotes: Bool
    public let enclosingCharacter: Character
    
    public init(delimiter: Character = ",", inQuotes: Bool = true, enclosingCharacter: Character = "\"") {
        self.delimiter = delimiter
        self.inQuotes = inQuotes
        self.enclosingCharacter = enclosingCharacter
    }
}
```

A couple of questions to consider: 
1. Should this be a separate struct for encoding vs. decoding?
2. Are you happy with the name `Config` for the struct? Happy to change it to something else. 
3. Should the struct be defined in a different location? Initially I was thinking it would only be a decode configuration so that's where it lived, but then I repurposed it for encode too and never moved it out of `Parser.swift`.

**Comment by daSkier** [comment]
Awesome. 

1. Great. I prefer that approach too. I figured I could restructure later.  
2. I think you're on the right track with the names. I think `cellSeparator` is good. `cellDelimiter` seems too similar since they map as similes in my mind and I wouldn't know the difference without looking at documentation. `cellWrapper` or `stringWrapper` or something else along those lines might be clearer for users. 
3. I think that makes sense. 
4. I already started these changes last night. I just didn't get a chance to finish them and push up the changes. I'll push up the changes once it's complete. 
5. Sounds good. 
Last: Whoops! I was worried I might forget about those. I'll pull out any misc print statements.

**Comment by daSkier** [comment]
@calebkleveter I've implemented the changes you suggested. I still feel that cellSeparator and cellDelimiter could be hard to understand for new comers, but I'm fine with it. 
- [x] 1. Let's put the Config struct in its own Config.swift file.

- [x] 2. I think we should rename a couple of the Config properties. delimiter => cellSeparator and enclosingCharacter => cellDelimiter.

- [x] 3. Let's just get rid of the Config.inQuotes property. Instead we can make cellDelimiter optional. If there is no configured delimiter, we'll assume that the cells are not wrapped.

- [x] 4. A Config should only be passed to a type through the initializer. It keeps things cleaner when you don't have to pass it into every method call.

- [x] 5. In Config, we should store the character byte values (UInt8) instead of the actual character for now. In the future, we may change the parser;/serializer to use Character arrays, but not for now.

P.S. Hopefully I pulled all the `print` statements this time 😬

**Comment by daSkier** [comment]
@calebkleveter 
1. API Docs: I think I got all of the public instances
2. `Config.default`: I implemented this the same way `DecodingOptions.default` is done and updated the init functions to now use `Config.default` rather than `Config()`. The `Config.default` uses the values of `44` for `cellSeparator` and `34` as `cellDelimiter` as you suggested, but I'm wondering if nil should be the default value for `cellDelimiter` instead. It seems to me that most users wouldn't  expect CSV output to have the quotation mark wrappers by default, but 🤷‍♂️.
3. `Parser.parse(_:length:)`: Now updated for `cellDelimiter`

**Pull request merged**
